name: Linux CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install python3-setuptools
      run:  sudo apt-get install python3-setuptools
    - name: install conan
      run:  sudo pip3 install conan && source ~/.profile
    - name: build
      run: ./build.sh
